PILOT-1837: Add support for multiple types in notification filtering
PilotDataPlatform/bff-web pull request #163
Opened 2022-11-22 09:49 UTC by vmoshynskyi

## Summary

Add support multiple types in notification filtering

## JIRA Issues

PILOT-1837

## Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)

## Testing

Are there any new or updated tests to validate the changes?

- [x] Yes
- [ ] No

2022-11-22 17:29 UTC, hugoantunes requested changes

2022-11-22 17:29 UTC, hugoantunes commented on api/api_notification/notification.py
> +        if notification_type is None:
What do you think if we move this switch to the `notification_service_client`?

2022-11-23 15:06 UTC, vmoshynskyi commented on api/api_notification/notification.py
> +        if notification_type is None:
Good point. I've moved notification params logic into filtering params class. Please check.

2022-11-23 15:10 UTC, hugoantunes approved these changes

2022-11-23 15:11 UTC, merged